### ISSUE TITLE
mttonucratiocalculator 0.7 does not work with EAGER-CLI 1.92.55

### ISSUE THREAD

**Issue by alexreg** [apeltzer/EAGER-links#1]
I'm not clear about which version of mttonucratiocalculator that EAGER-CLI 1.92.55 expects, since EAGER it seems to pass it 3 arguments, whereas mttonucratiocalculator only expects two.

```
$ mttonucratiocalculator /tmp/ArzelierEtAl2024/eager/BOU13/results/5-DeDup/BOU13_S8_R1_001.fastq.merged.fq.mappedonly.sorted.cleaned_rmdup.sorted.bam /tmp/ArzelierEtAl2024/eager/BOU13/results/5-DeDup MT
Version: 0.7
Please provide the (coordinate) sorted input SAM File, as well as the MT identifier. No further parameters are necessary! 

Make sure that your input file has an appropriate SAM/BAM file header, or the SAMRecords will be set to '*'! 
```

Furthermore, if I manually run this command but remove the second argument, I get an error.

```
Exception in thread "main" java.lang.NullPointerException
	at MTtoNucCalculator.getMTLength(MTtoNucCalculator.java:138)
	at MTtoNucCalculator.<init>(MTtoNucCalculator.java:52)
	at MTtoNucCalculator.main(MTtoNucCalculator.java:71)
```

Any clarification would be appreciated.

**Comment by alexreg** [comment]
Okay, well the second problem at least is now fixed in [my PR here](https://github.com/apeltzer/MTNucRatioCalculator/pull/4).

**Comment by apeltzer** [comment]
I would also advise to using https://nf-co.re/eager these days instead of the old EAGERv1 pipeline.
